export const defaultHiddenColumnNames = [
  "parentRowId",
  "rowItemId",
  "cTag",
  "quantum",
  "jsonTableId",
  "dimension",
  "currencyName",
  "colItemIds",
  "colItemIds",
  "2019Q3_parsedDataId",
  "2018Q3_parsedDataId",
  "2019M9_parsedDataId",
  "2018M9_parsedDataId",
];
